jobs:
  build:
    docker:
      - image: circleci/node:10.17

    working_directory: ~/jason-zhang

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
    #   - run: npm test
  deploy:
    docker:
        - image: circleci/node:10.17
    working_directory: ~/jason-zhang
    steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
        - run:
            name: Deploy Master to github pages
            command: npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master